#!/usr/bin/env python3
"""Encode a 9x9 Sudoku as DIMACS CNF or decode a NitroSAT assignment."""

import argparse


SIZE = 9


def variable(row, column, digit):
    """Map one-based (row, column, digit) to DIMACS variable 1..729."""
    return (row - 1) * 81 + (column - 1) * 9 + digit


def decode_variable(value):
    value -= 1
    return value // 81 + 1, (value % 81) // 9 + 1, value % 9 + 1


def read_puzzle(path):
    rows = []
    with open(path, encoding="ascii") as source:
        for line in source:
            symbols = [character for character in line if character in "1234567890."]
            if symbols:
                if len(symbols) != SIZE:
                    raise ValueError("each Sudoku row must contain exactly nine cells")
                rows.append(symbols)
    if len(rows) != SIZE:
        raise ValueError("the puzzle must contain exactly nine rows")
    return rows


def encode(puzzle_path, cnf_path):
    puzzle = read_puzzle(puzzle_path)
    clauses = []

    # Every cell contains at least one digit and at most one digit.
    for row in range(1, 10):
        for column in range(1, 10):
            clauses.append([variable(row, column, digit) for digit in range(1, 10)])
            for first in range(1, 10):
                for second in range(first + 1, 10):
                    clauses.append([-variable(row, column, first),
                                    -variable(row, column, second)])

    # Every digit occurs in every row and every column. Combined with exactly
    # one digit per cell, this also implies at most one occurrence.
    for digit in range(1, 10):
        for row in range(1, 10):
            clauses.append([variable(row, column, digit) for column in range(1, 10)])
        for column in range(1, 10):
            clauses.append([variable(row, column, digit) for row in range(1, 10)])

    # Every 3x3 box contains every digit.
    for digit in range(1, 10):
        for box_row in range(3):
            for box_column in range(3):
                clauses.append([
                    variable(box_row * 3 + row, box_column * 3 + column, digit)
                    for row in range(1, 4)
                    for column in range(1, 4)
                ])

    # Given cells become unit clauses.
    for row, symbols in enumerate(puzzle, start=1):
        for column, symbol in enumerate(symbols, start=1):
            if symbol not in "0.":
                clauses.append([variable(row, column, int(symbol))])

    with open(cnf_path, "w", encoding="ascii") as output:
        output.write("c 9x9 Sudoku generated by examples/v3/sudoku.py\n")
        output.write(f"p cnf {SIZE ** 3} {len(clauses)}\n")
        for clause in clauses:
            output.write(" ".join(map(str, clause)) + " 0\n")
    print(f"wrote {cnf_path}: 729 variables, {len(clauses)} clauses")


def decode(solution_path):
    selected = {}
    with open(solution_path, encoding="ascii") as source:
        for token in source.read().split():
            literal = int(token)
            if literal == 0:
                break
            if literal > 0 and literal <= SIZE ** 3:
                row, column, digit = decode_variable(literal)
                selected[(row, column)] = digit
    if len(selected) != SIZE * SIZE:
        raise ValueError(f"assignment selected {len(selected)} cells instead of 81")
    separator = "+-------+-------+-------+"
    print(separator)
    for row in range(1, 10):
        values = [str(selected[(row, column)]) for column in range(1, 10)]
        print("| " + " ".join(values[0:3]) + " | " + " ".join(values[3:6]) +
              " | " + " ".join(values[6:9]) + " |")
        if row % 3 == 0:
            print(separator)


def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    encode_parser = subparsers.add_parser("encode")
    encode_parser.add_argument("puzzle")
    encode_parser.add_argument("cnf")
    decode_parser = subparsers.add_parser("decode")
    decode_parser.add_argument("solution")
    arguments = parser.parse_args()
    if arguments.command == "encode":
        encode(arguments.puzzle, arguments.cnf)
    else:
        decode(arguments.solution)


if __name__ == "__main__":
    main()
